<a href="https://colab.research.google.com/github/chriswarren31/super-smashing-great-portfolio/blob/main/L6_BSc_Data_Science_M6T3_Introduction_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![data_assembly.png]()

<h3><font color="#AA00BB">How you can use this Notebook</font></h3>
<p>This notebook was written to teach new concepts in data using Python.</p>
<p>You can read through the descriptions run the code (it should work!), or you may be taken through the code by one of our experts.</p>
<p>But one of the best habits to acquire is to re-write the code yourself.</p>
<ul><li>Experiment
<li>Break the code
<li>Build a deeper understanding of both the underlying data concepts and the code</ul>
<p>Don't worry if you make mistakes, we all do. The way to get better and make less mistakes is to write more code.</p>
<p>Enjoy!</p>
<p> - <i><font color="#AA00BB">Data Assembly team.</font></i></p>
<br>

> ❓🤔 = a question for us discuss

> ⌨️ = a task for you to try

> 🔑 = an authoritative reference or guide you may find useful

> 🚀 = **optional** material to develop yourself further

<a name="contents"></a>
## **Contents**

<br>1. [Introduction to Pandas and DataFrames](#section_1)
<br>2. [Import and Export Data](#section_2)
<br>3. [Data Cleaning](#section_3)
<br>4. [Data Manipulation, Subsetting and Indexing](#section_4)
<br>5. [Sorting, grouping, and aggregating data](#section_6)
<br>6. [Combining DataFrames in Pandas: Merge, Join, Concat](#section_6)

Let's get started!🚀

<h2><font color="#AA00BB">Welcome to our workbook on Pandas: A Practical Guide!</font></h2>

## **What is Pandas?**

Pandas is a powerful data manipulation and analysis library for Python. It provides fast, flexible, and expressive data structures designed to work with both "relational" and "labeled" data. It is a fundamental package for data science, machine learning, and analytics. With Pandas, you can clean, transform, and aggregate your data efficiently, and then proceed to visualise it or use it in sophisticated models.

If you haven't installed Pandas yet, you can do so using pip:



```
pip install pandas
```

To use Pandas in your Python code, you first need to **import** the library:

In [ ]:
import pandas as pd

# The pd alias is a conventional shorthand used by the Python community.

🔑
- Learn all the many features of Pandas from the **official documentation** here. https://pandas.pydata.org/docs/reference/index.html
- Or follow the excellent Offiical Kaggle tutorial - https://www.kaggle.com/learn/pandas

# **1. Introduction to Pandas and DataFrames**
[Return to contents](#contents)

Pandas plays a pivotal role in data science and analytics for several compelling reasons, including:
- Data Cleaning
- Data Transformation
- Data Analysis
- Supporting the creation of charts and visualisations


#### **What is a DataFrame?**

A DataFrame is one of the primary data structures in Pandas. Think of it as an in-memory representation of an Excel spreadsheet or a SQL table, but with much more flexibility and functionality. A DataFrame is a 2-dimensional labeled data structure with columns that can be of different types (numeric, string, boolean, etc.).

An example of a DataFrame column (an individual column is also a Pandas **data series**)

![image.png]()

# **2. Loading (importing) and exporting Data**

Before you can perform any magic with data, you need to get it into your environment. Importing data is the first step in this direction. Let's delve into how to import data from different formats like CSV, Excel, and SQL Databases into Pandas.

**Reading CSV**: Use `pd.read_csv(`) to read CSV files quickly.

In [ ]:
import pandas as pd

# We can easily load CSV files with Pandas, either from a URL or a file stored on your system.
url_csv = 'https://raw.githubusercontent.com/BPP-Digital-Advanced-Data-Analytics/public_datasets/main/fitconstructor/user_data.csv'

# Load data from a CSV file
df = pd.read_csv(url_csv)

# Display the first 5 rows of the DataFrame
df.head(10)

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial,Unnamed: 10
0,0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR",23/10/1960,m*****ka@yahoo.com,171,49,02/03/2022,SN0000,NaN
1,1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL",25/09/1995,m*******sa@gmail.com,164,53,29/01/2022,SN0001,NaN
2,2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA",22/03/1966,l******be@hotmail.com,177,87,13/03/2022,SN0002,NaN
3,3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA",22/04/1975,m******ki@hotmail.com,179,76,05/12/2021,SN0003,NaN
4,4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU",20/04/1978,k*****ta@gmail.com,182,82,09/02/2022,SN0004,NaN
5,5,Tony Moore,male,"Flat 4, Miah plaza, New Judithville, FY1 3AA",10/11/2001,t******m64@yahoo.com,181,75,21/01/2022,SN0005,NaN
6,6,Dr Ronald Potter,male,"Flat 81k, Charlie islands, West Janethaven, BS...",18/03/1970,d****r1@gmail.com,176,49,04/12/2021,SN0006,NaN
7,7,Ryan Begum,male,"Flat 8, Judith burgs, Taylorside, SK1 4NB",13/01/1965,r*****b65@gmail.com,182,62,05/02/2022,SN0007,NaN
8,8,Connor Bell,male,"8 Josh ranch, Daviesstad, BD10 9HX",26/10/1961,c****be@gmail.com,184,74,23/01/2022,SN0008,NaN
9,9,Eric Young,male,"Studio 66, Hyde ways, Taylortown, TA1 1XQ",02/04/1966,e******y70@hotmail.com,176,65,30/03/2022,SN0009,NaN

#### **Importing Data from Excel**

You can also read Excel files with Pandas, you can use the `read_excel() `function.

**Note**: Make sure you have the **openpyxl** library installed to read .xlsx files.

In [ ]:
# Create a simple HTML file using python to create the *.html file
title = "My Web Page"
header = "Welcome to My Web Page!"
paragraph = "This is a simple Python-generated HTML page."

html = f"""
<html>
    <head>
        <title>{title}</title>
    </head>
    <body>
        <h1>{header}</h1>
        <p>{paragraph}</p>
    </body>
</html>
"""

# Write the HTML code to a file
with open("my_web_page.html", "w") as file:
    file.write(html)

### **Exporting Data**
After you've manipulated or analysed your data, you might want to export it to a file format of your choice. Pandas makes this easy as well.

**Exporting Data to CSV**
To save a DataFrame as a CSV file, use the `to_csv() `method:

In [ ]:
# Save DataFrame to a CSV file
df.to_csv('output_data.csv', index=False)

# Setting index=False prevents Pandas from writing row numbers into the CSV file.

You can see your saved CSV file here in the Colab File Manager.

![image.png]()

In [ ]:
data = pd.read_csv('output_data.csv')
data.head() # by default head outputs the first 5 rows

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial,Unnamed: 10
0,0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR",23/10/1960,m*****ka@yahoo.com,171,49,02/03/2022,SN0000,NaN
1,1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL",25/09/1995,m*******sa@gmail.com,164,53,29/01/2022,SN0001,NaN
2,2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA",22/03/1966,l******be@hotmail.com,177,87,13/03/2022,SN0002,NaN
3,3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA",22/04/1975,m******ki@hotmail.com,179,76,05/12/2021,SN0003,NaN
4,4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU",20/04/1978,k*****ta@gmail.com,182,82,09/02/2022,SN0004,NaN

## **⌨️Exercise**
Make the following changes to your web page.
1. Load the CSV file from this URL - https://raw.githubusercontent.com/BPP-Digital-Advanced-Data-Analytics/public_datasets/main/fitconstructor/crm.csv
2. Display the first 5 rows of data using head(), then use the function `tail()` to output the last 5 rows.
3. Save the file to your machine using the `to_csv() `function
4. Reload the file using `read_csv()`

#**3. Data Cleaning**

Data cleaning is the process of preparing your data for analysis by removing or modifying data that is incorrect, incomplete, irrelevant, duplicated, or improperly formatted. This is crucial because dirty data can lead to false conclusions and misinterpretations, including:
- Missing values
- Inconsistent formats
- Duplicate data
- Outliers

In real life this can look like:
- Duplicated customer records
- Missing information e.g. customers missing address info, or contact information
- Inconsistent data formats e.g. MM-DD-YY instead of DD-MM-YY

Let's get started and clean some data!🧹

## **3.1 Finding and Fixing Missing Values**

Missing data is a common problem faced in real world datasets. The first step in tackling missing data is finding it. By inspecting missing data, we can analyse it and sometimes even determine if there's a systemic issue that's causing it.

For example, we could discover all customers from a certain region were missing height and weight data, and you might conclude the collection method for that region is different or broken.

In [ ]:
import pandas as pd

df_messy = pd.read_csv('https://raw.githubusercontent.com/BPP-Digital-Advanced-Data-Analytics/public_datasets/main/fitconstructor/user_data_messy.csv')
df_messy.head(5)

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall,Mitchellside,B5 9PA",23/10/1960,m*****ka@yahoo.com,171.0,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
2,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
3,2,Lorraine Bentley,female,"Flat 89,Williams avenue,Katieville,SE10 0JT",22/03/1966,l******be@hotmail.com,NaN,87,13/03/2022,SN0002
4,3,Ms Kimberley Walker,female,"6 Cameron freeway,Beverleymouth,HD94 8BE",22/04/1975,m******ki@hotmail.com,179.0,76,05/12/2021,SN0003

**Notice** how the 4th data entry in height shows up as **NaN**. NaN is how pandas represents missing values and it's short for Not A Number.

In [ ]:
# Show missing values as True or False, this can be confusing to  look at
df_messy.isna()

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
247,False,False,False,False,False,False,False,False,False,False
248,False,False,False,False,False,False,False,False,False,False
249,False,False,False,False,False,False,False,False,False,False
250,False,False,False,False,False,False,True,False,False,False
251,False,False,False,False,False,False,False,False,False,False

In [ ]:
# So let's display rows where any element is missing
df_messy[df_messy.isna().any(axis=1)]

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
3,2,Lorraine Bentley,female,"Flat 89,Williams avenue,Katieville,SE10 0JT",22/03/1966,l******be@hotmail.com,NaN,87,13/03/2022,SN0002
12,11,Glen Foster,male,"11 James way,Dannytown,M7S 1TF",24/10/1996,g****fo@yahoo.com,NaN,77,26/02/2022,SN0011
31,29,Mr Antony Davey,male,"Studio 90L,Warner track,Mooreport,L1 4LQ",24/10/1961,m*******an@gmail.com,NaN,71,14/12/2021,SN0029
57,55,Joyce Evans,female,"7 Mohammed mission,South Ameliaport,DY91 4HP",04/11/1956,j******e@gmail.com,NaN,69,28/12/2021,SN0055
81,79,Dr Alison O'Connor,female,"Studio 11,Robinson lake,Lake Rickyton,HU3 3BG",03/04/1988,d*******a@yahoo.com,NaN,51,22/01/2022,SN0079
102,100,Mandy Middleton,female,"774 Morton trail,Davidmouth,M74 8TF",29/09/1971,m*******m@gmail.com,NaN,100,15/03/2022,SN0100
129,127,Olivia Bradley,female,"Studio 17,Page manor,Wardview,TD9V 2EE",24/11/1967,o******b@yahoo.com,NaN,46,13/01/2022,SN0127
171,169,Bruce Hughes,male,"502 Philip rapid,Williamschester,L8A 2LG",21/12/1968,b*******hu@gmail.com,NaN,62,05/03/2022,SN0169
198,196,Wayne Clark,male,"154 Peter drive,Port Jack,W50 8UT",05/02/1969,w*******cl40@yahoo.com,NaN,68,23/01/2022,SN0196
210,208,Joanna Field,female,"562 Maurice forks,South Nicole,N12 2EU",07/01/1991,j****fi@yahoo.com,NaN,53,07/03/2022,SN0208
228,226,Stanley Gray-Atkins,male,"48 Neil harbors,North Hazelton,N3 2GY",13/07/1957,s******gr@gmail.com,NaN,66,29/01/2022,SN0226
250,248,Sara Griffin,female,"0 Katie vista,Davieshaven,N3S 7FU",24/01/1991,s*******gr@hotmail.com,NaN,64,15/12/2021,SN0248

- `df_messy.isna()` checks each element in the DataFrame for missing values and returns a DataFrame of the same shape, but with True for missing values and False for others.

- `.any(axis=1)` checks each row to see if it has any True values, which would mean that row has at least one missing value.

- `df_messy[...]` filters the original DataFrame to only include rows that meet the condition set inside the square brackets, i.e., rows with any missing values.

### **To fix these missing value we can employ 3 Strategies**

1. **Removing Rows**: You can use `dropna(`) to remove rows with missing values.
2. **Filling Values:** Use `fillna(`) to fill missing values with a specified value or using a specified method (e.g. replace with 0 or the median value)
3. **Forward Fill or Backward Fill:** Use the `fillna()` method with method parameter as '`ffill`' or '`bfill`'. This copies the previous or next rows' value into the entry with missing data.

#### **Removing rows with missing data**

In [ ]:
# This removes the rows with missing data from our dataframe
df_messy.dropna()
# we can use df_messy.dropna(inplace=True) to remove and automatically update df_messy

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall,Mitchellside,B5 9PA",23/10/1960,m*****ka@yahoo.com,171.0,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
2,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
4,3,Ms Kimberley Walker,female,"6 Cameron freeway,Beverleymouth,HD94 8BE",22/04/1975,m******ki@hotmail.com,179.0,76,05/12/2021,SN0003
5,4,Kimberley Taylor,female,"Flat 0,Thomas trace,New Tom,E0 3BZ",20/04/1978,k*****ta@gmail.com,182.0,82,09/02/2022,SN0004
...,...,...,...,...,...,...,...,...,...,...
246,244,Joanna Newton,female,"95 Patrick manors,Barretttown,S5 6BY",08/05/1965,j******n@yahoo.com,177.0,62,28/02/2022,SN0244
247,245,Miss Janet Thomas,female,"Studio 0,Nicholas viaduct,North Tracey,M8 1PF",15/04/1997,m******j16@yahoo.com,164.0,67,20/12/2021,SN0245
248,246,Elliot Little,male,"6 Akhtar estates,Stevenfort,PR87 9YU",01/03/1944,e*******l@gmail.com,184.0,88,26/12/2021,SN0246
249,247,Miss Victoria Stevens,female,"Flat 46,Gibbs trafficway,Amandashire,M6D 2WB",05/07/1977,m******vi77@yahoo.com,182.0,69,08/02/2022,SN0247
251,249,Fiona Patel,female,"Studio 0,Patel pine,Mitchellside,G6 3QG",12/04/1952,f*****pa45@hotmail.com,158.0,57,21/03/2022,SN0249

#### **Using fill_na() to replace with the mean**

**Note:**
- `fill_na(value`) can replace the missing data with the any `value`
- We can use the inplace argument to replace our data, for example:
  - `df_messy['height_cm'].fillna(mean_value, inplace=True)`

In [ ]:
# Compute the mean of the 'height_cm' column
mean_value = df_messy['height_cm'].mean()

# Fill missing values in the 'Age' column with the mean
df_messy['height_cm'].fillna(mean_value)

0      171.00
1      164.00
2      164.00
3      169.25
4      179.00
        ...
247    164.00
248    184.00
249    182.00
250    169.25
251    158.00
Name: height_cm, Length: 252, dtype: float64

#### **We can also do foward and backward fills**

Notice how the 4th row under the height column takes the value of the previous above (164).

In [ ]:
df_messy.fillna(method='ffill')  # Forward fill

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall,Mitchellside,B5 9PA",23/10/1960,m*****ka@yahoo.com,171.0,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
2,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
3,2,Lorraine Bentley,female,"Flat 89,Williams avenue,Katieville,SE10 0JT",22/03/1966,l******be@hotmail.com,164.0,87,13/03/2022,SN0002
4,3,Ms Kimberley Walker,female,"6 Cameron freeway,Beverleymouth,HD94 8BE",22/04/1975,m******ki@hotmail.com,179.0,76,05/12/2021,SN0003
...,...,...,...,...,...,...,...,...,...,...
247,245,Miss Janet Thomas,female,"Studio 0,Nicholas viaduct,North Tracey,M8 1PF",15/04/1997,m******j16@yahoo.com,164.0,67,20/12/2021,SN0245
248,246,Elliot Little,male,"6 Akhtar estates,Stevenfort,PR87 9YU",01/03/1944,e*******l@gmail.com,184.0,88,26/12/2021,SN0246
249,247,Miss Victoria Stevens,female,"Flat 46,Gibbs trafficway,Amandashire,M6D 2WB",05/07/1977,m******vi77@yahoo.com,182.0,69,08/02/2022,SN0247
250,248,Sara Griffin,female,"0 Katie vista,Davieshaven,N3S 7FU",24/01/1991,s*******gr@hotmail.com,182.0,64,15/12/2021,SN0248
251,249,Fiona Patel,female,"Studio 0,Patel pine,Mitchellside,G6 3QG",12/04/1952,f*****pa45@hotmail.com,158.0,57,21/03/2022,SN0249

In [ ]:
df_messy.fillna(method='bfill')  # Backwards fill

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall,Mitchellside,B5 9PA",23/10/1960,m*****ka@yahoo.com,171.0,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
2,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
3,2,Lorraine Bentley,female,"Flat 89,Williams avenue,Katieville,SE10 0JT",22/03/1966,l******be@hotmail.com,179.0,87,13/03/2022,SN0002
4,3,Ms Kimberley Walker,female,"6 Cameron freeway,Beverleymouth,HD94 8BE",22/04/1975,m******ki@hotmail.com,179.0,76,05/12/2021,SN0003
...,...,...,...,...,...,...,...,...,...,...
247,245,Miss Janet Thomas,female,"Studio 0,Nicholas viaduct,North Tracey,M8 1PF",15/04/1997,m******j16@yahoo.com,164.0,67,20/12/2021,SN0245
248,246,Elliot Little,male,"6 Akhtar estates,Stevenfort,PR87 9YU",01/03/1944,e*******l@gmail.com,184.0,88,26/12/2021,SN0246
249,247,Miss Victoria Stevens,female,"Flat 46,Gibbs trafficway,Amandashire,M6D 2WB",05/07/1977,m******vi77@yahoo.com,182.0,69,08/02/2022,SN0247
250,248,Sara Griffin,female,"0 Katie vista,Davieshaven,N3S 7FU",24/01/1991,s*******gr@hotmail.com,158.0,64,15/12/2021,SN0248
251,249,Fiona Patel,female,"Studio 0,Patel pine,Mitchellside,G6 3QG",12/04/1952,f*****pa45@hotmail.com,158.0,57,21/03/2022,SN0249

### **3.2 Finding and removing duplicates** **bold text**

In [ ]:
# First let's show all duplicate rows
df_messy[df_messy.duplicated(keep=False)]

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
2,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
14,13,Brenda Harris,female,"2 Clifford glens,Emilyhaven,WF2R 5YF",15/12/1965,b*****h62@gmail.com,158.0,49,09/12/2021,SN0013
15,13,Brenda Harris,female,"2 Clifford glens,Emilyhaven,WF2R 5YF",15/12/1965,b*****h62@gmail.com,158.0,49,09/12/2021,SN0013

To **remove** duplicates simple use `drop_duplicates()` use the inplace=True arguement to update your dataframe.

In [ ]:
df_messy.drop_duplicates() #df.drop_duplicates(inplace=True)

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall,Mitchellside,B5 9PA",23/10/1960,m*****ka@yahoo.com,171.0,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
3,2,Lorraine Bentley,female,"Flat 89,Williams avenue,Katieville,SE10 0JT",22/03/1966,l******be@hotmail.com,NaN,87,13/03/2022,SN0002
4,3,Ms Kimberley Walker,female,"6 Cameron freeway,Beverleymouth,HD94 8BE",22/04/1975,m******ki@hotmail.com,179.0,76,05/12/2021,SN0003
5,4,Kimberley Taylor,female,"Flat 0,Thomas trace,New Tom,E0 3BZ",20/04/1978,k*****ta@gmail.com,182.0,82,09/02/2022,SN0004
...,...,...,...,...,...,...,...,...,...,...
247,245,Miss Janet Thomas,female,"Studio 0,Nicholas viaduct,North Tracey,M8 1PF",15/04/1997,m******j16@yahoo.com,164.0,67,20/12/2021,SN0245
248,246,Elliot Little,male,"6 Akhtar estates,Stevenfort,PR87 9YU",01/03/1944,e*******l@gmail.com,184.0,88,26/12/2021,SN0246
249,247,Miss Victoria Stevens,female,"Flat 46,Gibbs trafficway,Amandashire,M6D 2WB",05/07/1977,m******vi77@yahoo.com,182.0,69,08/02/2022,SN0247
250,248,Sara Griffin,female,"0 Katie vista,Davieshaven,N3S 7FU",24/01/1991,s*******gr@hotmail.com,NaN,64,15/12/2021,SN0248
251,249,Fiona Patel,female,"Studio 0,Patel pine,Mitchellside,G6 3QG",12/04/1952,f*****pa45@hotmail.com,158.0,57,21/03/2022,SN0249

### **3.3 Finding and Removing Outliers**

Outliers can often be identified by looking at the statistical distribution of a column or if it exceeds a predefined range (e.g. age for adults could be limited to 18 to 120 years old).

- **Out of predefined range**
- **Percentiles**
- **Z-Score:** Any data point that has a Z-score greater than 3 or less than -3 is considered an outlier.
- **IQR (Interquartile Range**): Any data point below **Q1-1.5 x IQR** or **Q3+1.5 x IQR** is considered an outlier.


![image.png]()


You can remove outliers like so:

#### **Checking to see which values are out of range**

**Note** there is no inplace operation for these so to update your dataframe you'll need to filter on the desired range and use the `=` operator to assign the variable name to the new dataframe.
- `df = df[df['column_name'] <= 100]`

In [ ]:
df_messy[df_messy['weight_kg'] >= 250]

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
62,60,Colin Singh,male,"5 Harriet islands,East Sheilaside,WA1 9ER",20/03/1955,c****s@hotmail.com,161.0,754,02/12/2021,SN0060
127,125,Dr Joe Curtis,male,"066 West junctions,North Mitchell,FK5 3DT",30/07/1996,d*******j@gmail.com,150.0,4362,08/01/2022,SN0125

In [ ]:
df_messy[(df_messy['weight_kg'] >= 30) & (df_messy['weight_kg'] <= 500)]

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall,Mitchellside,B5 9PA",23/10/1960,m*****ka@yahoo.com,171.0,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
2,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
3,2,Lorraine Bentley,female,"Flat 89,Williams avenue,Katieville,SE10 0JT",22/03/1966,l******be@hotmail.com,NaN,87,13/03/2022,SN0002
4,3,Ms Kimberley Walker,female,"6 Cameron freeway,Beverleymouth,HD94 8BE",22/04/1975,m******ki@hotmail.com,179.0,76,05/12/2021,SN0003
...,...,...,...,...,...,...,...,...,...,...
247,245,Miss Janet Thomas,female,"Studio 0,Nicholas viaduct,North Tracey,M8 1PF",15/04/1997,m******j16@yahoo.com,164.0,67,20/12/2021,SN0245
248,246,Elliot Little,male,"6 Akhtar estates,Stevenfort,PR87 9YU",01/03/1944,e*******l@gmail.com,184.0,88,26/12/2021,SN0246
249,247,Miss Victoria Stevens,female,"Flat 46,Gibbs trafficway,Amandashire,M6D 2WB",05/07/1977,m******vi77@yahoo.com,182.0,69,08/02/2022,SN0247
250,248,Sara Griffin,female,"0 Katie vista,Davieshaven,N3S 7FU",24/01/1991,s*******gr@hotmail.com,NaN,64,15/12/2021,SN0248
251,249,Fiona Patel,female,"Studio 0,Patel pine,Mitchellside,G6 3QG",12/04/1952,f*****pa45@hotmail.com,158.0,57,21/03/2022,SN0249

#### **Now let's explore percentile ranges**

In [ ]:
lower_bound = df_messy['weight_kg'].quantile(0.025)
upper_bound = df_messy['weight_kg'].quantile(0.975)
df_messy[(df_messy['weight_kg'] >= lower_bound) & (df_messy['weight_kg'] <= upper_bound)]

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall,Mitchellside,B5 9PA",23/10/1960,m*****ka@yahoo.com,171.0,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
2,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
3,2,Lorraine Bentley,female,"Flat 89,Williams avenue,Katieville,SE10 0JT",22/03/1966,l******be@hotmail.com,NaN,87,13/03/2022,SN0002
4,3,Ms Kimberley Walker,female,"6 Cameron freeway,Beverleymouth,HD94 8BE",22/04/1975,m******ki@hotmail.com,179.0,76,05/12/2021,SN0003
...,...,...,...,...,...,...,...,...,...,...
247,245,Miss Janet Thomas,female,"Studio 0,Nicholas viaduct,North Tracey,M8 1PF",15/04/1997,m******j16@yahoo.com,164.0,67,20/12/2021,SN0245
248,246,Elliot Little,male,"6 Akhtar estates,Stevenfort,PR87 9YU",01/03/1944,e*******l@gmail.com,184.0,88,26/12/2021,SN0246
249,247,Miss Victoria Stevens,female,"Flat 46,Gibbs trafficway,Amandashire,M6D 2WB",05/07/1977,m******vi77@yahoo.com,182.0,69,08/02/2022,SN0247
250,248,Sara Griffin,female,"0 Katie vista,Davieshaven,N3S 7FU",24/01/1991,s*******gr@hotmail.com,NaN,64,15/12/2021,SN0248
251,249,Fiona Patel,female,"Studio 0,Patel pine,Mitchellside,G6 3QG",12/04/1952,f*****pa45@hotmail.com,158.0,57,21/03/2022,SN0249

#### **Using Z-scores and Inter Quartile Rnages**

In [ ]:
# We can use the SciPy and Numpy library for this
from scipy import stats
import numpy as np

df_messy[(np.abs(stats.zscore(df_messy['weight_kg'])) < 3)]

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall,Mitchellside,B5 9PA",23/10/1960,m*****ka@yahoo.com,171.0,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
2,1,Mr Sam Simmons,male,"Studio 77U,Arthur lock,Tomchester,B22 4DL",25/09/1995,m*******sa@gmail.com,164.0,53,29/01/2022,SN0001
3,2,Lorraine Bentley,female,"Flat 89,Williams avenue,Katieville,SE10 0JT",22/03/1966,l******be@hotmail.com,NaN,87,13/03/2022,SN0002
4,3,Ms Kimberley Walker,female,"6 Cameron freeway,Beverleymouth,HD94 8BE",22/04/1975,m******ki@hotmail.com,179.0,76,05/12/2021,SN0003
...,...,...,...,...,...,...,...,...,...,...
247,245,Miss Janet Thomas,female,"Studio 0,Nicholas viaduct,North Tracey,M8 1PF",15/04/1997,m******j16@yahoo.com,164.0,67,20/12/2021,SN0245
248,246,Elliot Little,male,"6 Akhtar estates,Stevenfort,PR87 9YU",01/03/1944,e*******l@gmail.com,184.0,88,26/12/2021,SN0246
249,247,Miss Victoria Stevens,female,"Flat 46,Gibbs trafficway,Amandashire,M6D 2WB",05/07/1977,m******vi77@yahoo.com,182.0,69,08/02/2022,SN0247
250,248,Sara Griffin,female,"0 Katie vista,Davieshaven,N3S 7FU",24/01/1991,s*******gr@hotmail.com,NaN,64,15/12/2021,SN0248
251,249,Fiona Patel,female,"Studio 0,Patel pine,Mitchellside,G6 3QG",12/04/1952,f*****pa45@hotmail.com,158.0,57,21/03/2022,SN0249

### **3.4 Now let's check our column types to be sure Pandas has interpreted the datatypes correctly**

In [ ]:
# View Pandas datatypes
df_messy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              252 non-null    int64
 1   name                 252 non-null    object
 2   gender               252 non-null    object
 3   address              252 non-null    object
 4   date_of_birth        252 non-null    object
 5   email_address        252 non-null    object
 6   height_cm            240 non-null    float64
 7   weight_kg            252 non-null    int64
 8   account_create_date  252 non-null    object
 9   bike_serial          252 non-null    object
dtypes: float64(1), int64(2), object(7)
memory usage: 19.8+ KB

We can spot two issues:
1. We can see our data_of_birth column is stored as an object. Pandas has a datetime data type so let's change it.  
2. We see height is float64 type. We don't need to store height at a decimal level so let's change that to an int64 type.

In [ ]:
df_messy['height_cm'] = df_messy['height_cm'].astype('int')
df_messy

IntCastingNaNError: ignored

You will encounter an error. This is because we haven't fixed our missing data......you'll have to do this in the upcoming exercise.

#### **Let's change the date_of_birth column to a DateTime data type**

In [ ]:
df_messy['date_of_birth'] = pd.to_datetime(df_messy['date_of_birth'])

# Let's see if the operation completed successfully
df_messy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              252 non-null    int64
 1   name                 252 non-null    object
 2   gender               252 non-null    object
 3   address              252 non-null    object
 4   date_of_birth        252 non-null    datetime64[ns]
 5   email_address        252 non-null    object
 6   height_cm            240 non-null    float64
 7   weight_kg            252 non-null    int64
 8   account_create_date  252 non-null    object
 9   bike_serial          252 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 19.8+ KB

<ipython-input-31-46eba1d95772>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_messy['date_of_birth'] = pd.to_datetime(df_messy['date_of_birth'])

## **⌨️Exercise**
Make the following changes to your web page.
1. Load the CSV file from this URL - https://raw.githubusercontent.com/BPP-Digital-Advanced-Data-Analytics/public_datasets/main/fitconstructor/user_data_messy.csv
2. Perform the following to clean the dataset
   - Fill all missing values with the median values
   - Remove all duplicates
   - Change the column data types to the appropriate data types (date should datetime and numeric columns should be integers)
   - Remove all outliers using a method of choice

# **4. Data manipulation and subsetting**

Indexing and Slicing DataFarmes are quite powerful and enable us to:
1. Extract only relevant columns for the analysis.
2. Add and remove columns or rows.
3. Edit individual data points.

### **4.1 Selecting data Using .loc[] and .iloc[]**

Pandas provides two essential methods for selecting data: `.loc[]` and` .iloc[]`. These methods are your keys to unlocking data within your DataFrame.

#### **The .loc[] method**

The `.loc[]` method allows you to select data based on its label or name, in both the row and column dimensions. In our example:

In [ ]:
import pandas as pd

# We can easily load CSV files with Pandas, either from a URL or a file stored on your system.
url_csv = 'https://raw.githubusercontent.com/BPP-Digital-Advanced-Data-Analytics/public_datasets/main/fitconstructor/user_data.csv'

# Load data from a CSV file
df = pd.read_csv(url_csv)

df.head()

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial,Unnamed: 10
0,0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR",23/10/1960,m*****ka@yahoo.com,171,49,02/03/2022,SN0000,NaN
1,1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL",25/09/1995,m*******sa@gmail.com,164,53,29/01/2022,SN0001,NaN
2,2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA",22/03/1966,l******be@hotmail.com,177,87,13/03/2022,SN0002,NaN
3,3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA",22/04/1975,m******ki@hotmail.com,179,76,05/12/2021,SN0003,NaN
4,4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU",20/04/1978,k*****ta@gmail.com,182,82,09/02/2022,SN0004,NaN

In [ ]:
# Select the first row of the 'name' column
df.loc[0,'name']

'Mrs Katie Hudson'

Here, 0 refers to the row index and `'name'` refers to the column name. So when we use `.loc[0, 'name'`], we are specifically asking Pandas to give us the data that sits in the intersection of the first row `(index 0)` and the column named `'name'`.

In simpler terms, it's like saying, "Hey, Pandas! Could you please fetch me the name of the product that's listed in the first row of the DataFrame?"

The `loc` attribute allows you to select both rows and columns by labels. If you want to select all rows and some columns, you can do:

In [ ]:
selected_columns = df.loc[:, ['name', 'gender']]
selected_columns.head()

                  name  gender
0     Mrs Katie Hudson  female
1       Mr Sam Simmons    male
2     Lorraine Bentley  female
3  Ms Kimberley Walker  female
4     Kimberley Taylor  female

### **.iloc[] for integer-dased indexing**

On the other hand, .`iloc[]` works based on integer-based positions for both rows and columns. It doesn't care about the labels or names; it simply goes by the position

In [ ]:
# Let's output the value of the 2nd row, 4th column
df.iloc[2,4]

'22/03/1966'

In [ ]:
# Select all rows and the first four columns using iloc
selected_columns = df.iloc[:, :4]
selected_columns.head()

,user_id,name,gender,address
0,0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR"
1,1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL"
2,2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA"
3,3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA"
4,4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU"

### **Selecting by Column Names**

In [ ]:
# Select columns by their names
selected_columns = df[['name', 'date_of_birth']]
selected_columns.head()

                  name date_of_birth
0     Mrs Katie Hudson    23/10/1960
1       Mr Sam Simmons    25/09/1995
2     Lorraine Bentley    22/03/1966
3  Ms Kimberley Walker    22/04/1975
4     Kimberley Taylor    20/04/1978

### **Adding and Dropping Columns**

Adding and dropping columns is extremely useful in Pandas.

Let's create a column for Body Mass Index (BMI) and add it to our dataframe.

In [ ]:
# Convert height from cm to m
df['Height_m'] = df['height_cm'] / 100

# Calculate BMI
df['BMI'] = df['weight_kg'] / (df['Height_m'] ** 2)
df.head()

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial,Unnamed: 10,Height_m,BMI
0,0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR",23/10/1960,m*****ka@yahoo.com,171,49,02/03/2022,SN0000,NaN,1.71,16.757293
1,1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL",25/09/1995,m*******sa@gmail.com,164,53,29/01/2022,SN0001,NaN,1.64,19.705532
2,2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA",22/03/1966,l******be@hotmail.com,177,87,13/03/2022,SN0002,NaN,1.77,27.769798
3,3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA",22/04/1975,m******ki@hotmail.com,179,76,05/12/2021,SN0003,NaN,1.79,23.719609
4,4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU",20/04/1978,k*****ta@gmail.com,182,82,09/02/2022,SN0004,NaN,1.82,24.755464

#### **Removing columns**

If you created a temporary column for height in meters (Height_m) and wish to remove it, you can do so using the drop method.

In [ ]:
df.drop(columns=['Height_m'], inplace=True)
df.head()

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial,Unnamed: 10,BMI
0,0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR",23/10/1960,m*****ka@yahoo.com,171,49,02/03/2022,SN0000,NaN,16.757293
1,1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL",25/09/1995,m*******sa@gmail.com,164,53,29/01/2022,SN0001,NaN,19.705532
2,2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA",22/03/1966,l******be@hotmail.com,177,87,13/03/2022,SN0002,NaN,27.769798
3,3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA",22/04/1975,m******ki@hotmail.com,179,76,05/12/2021,SN0003,NaN,23.719609
4,4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU",20/04/1978,k*****ta@gmail.com,182,82,09/02/2022,SN0004,NaN,24.755464

## **⌨️Exercise**
1. Create a column that has converted `height_cm` and `weight_kf` to height in inches and weight in pounds (lbs).
2. Select and create a dataframe showing only the customers between 160cm and 175cm
  - **HINT** - This code fitlers between persons 20 to 200cm.
`filtered_df = df[(df['Height_cm'] >= 20) & (df['Height_cm'] <= 200)]`
3. Select and create a dataframe showing only the female customers.
  - **HINT** - This code fitlers on male customers  
`filtered_df = df[df['gender'] == 'male']`

# **5. Sorting, grouping, and aggregating data with Pandas**

## **5.1 Why sort data?**

Sorting helps you quickly identify patterns or outliers in your data. For instance, you might want to know the youngest and oldest patients in your dataset. Here is a simple example of sorting data based on age:

In [ ]:
import pandas as pd

# We can easily load CSV files with Pandas, either from a URL or a file stored on your system.
url_csv = 'https://raw.githubusercontent.com/BPP-Digital-Advanced-Data-Analytics/public_datasets/main/fitconstructor/user_data.csv'

# Load data from a CSV file
df = pd.read_csv(url_csv)
df.drop(columns = 'Unnamed: 10', inplace=True)
df.head()

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
0,0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR",23/10/1960,m*****ka@yahoo.com,171,49,02/03/2022,SN0000
1,1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL",25/09/1995,m*******sa@gmail.com,164,53,29/01/2022,SN0001
2,2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA",22/03/1966,l******be@hotmail.com,177,87,13/03/2022,SN0002
3,3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA",22/04/1975,m******ki@hotmail.com,179,76,05/12/2021,SN0003
4,4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU",20/04/1978,k*****ta@gmail.com,182,82,09/02/2022,SN0004

#### **Let's sort on height**

In [ ]:
df.sort_values('height_cm')

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
125,125,Dr Joe Curtis,male,"066 West junctions, North Mitchell, BT32 5JX",30/07/1996,d*******j@gmail.com,150,42,08/01/2022,SN0125
19,19,Chelsea Ellis-Kelly,female,"Flat 8, Butler ports, North Geraldinemouth, IV...",07/10/1964,c****el@hotmail.com,150,56,27/03/2022,SN0019
197,197,Mr Mohammed Fisher,male,"81 John key, East Cameron, PL1 1DS",02/03/1953,m******m32@hotmail.com,151,43,30/01/2022,SN0197
98,98,Shannon Harris,female,"982 Stevens circles, New Joanne, M33 4GW",17/10/1993,s*******ha@gmail.com,151,54,12/01/2022,SN0098
201,201,Beth Flynn,female,"0 Atkinson springs, Murphyfort, WF1 5SY",28/07/1945,b*******fl@yahoo.com,151,47,31/12/2021,SN0201
...,...,...,...,...,...,...,...,...,...,...
207,207,Mrs Rebecca Iqbal,female,"Studio 54, Yvonne stream, Lake Owenstad, BT44 0DY",24/08/1994,m*******r@yahoo.com,189,85,15/03/2022,SN0207
44,44,Catherine Patel,female,"27 Wilkinson garden, West Edward, SA72 6XQ",22/08/1964,c******p8@gmail.com,189,82,01/01/2022,SN0044
29,29,Mr Antony Davey,male,"Studio 90L, Warner track, Mooreport, UB1 2QL",24/10/1961,m*******an@gmail.com,189,71,14/12/2021,SN0029
100,100,Mandy Middleton,female,"774 Morton trail, Davidmouth, WF9 4RY",29/09/1971,m*******m@gmail.com,189,100,15/03/2022,SN0100
248,248,Sara Griffin,female,"0 Katie vista, Davieshaven, ST5 5AT",24/01/1991,s*******gr@hotmail.com,189,64,15/12/2021,SN0248

#### **We can sort string data types too**

In [ ]:
df.sort_values('name')

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
160,160,Adrian Hunter,male,"Flat 4, Adam avenue, Marianburgh, WR13 6PZ",07/09/1966,a*****hu73@gmail.com,173,65,15/03/2022,SN0160
235,235,Adrian King-Ferguson,male,"Flat 94, Barbara knolls, Brianfort, ME9 8JZ",24/04/1967,a******ki@yahoo.com,157,49,19/01/2022,SN0235
133,133,Alan Evans,male,"6 Charlton glens, Hollyton, DH4 7AY",15/03/1974,a******e@yahoo.com,174,42,10/03/2022,SN0133
116,116,Alice Bell,female,"Flat 4, Baker ranch, Port Clare, BT66 8BW",09/05/1999,a*****be@yahoo.com,156,60,15/02/2022,SN0116
94,94,Alison Davies,female,"Flat 35, Keith mountains, Simmonsmouth, N1 4HD",26/08/1964,a*******d@gmail.com,167,66,30/03/2022,SN0094
...,...,...,...,...,...,...,...,...,...,...
80,80,Victor Houghton,male,"715 Robert vista, East Conor, FY1 9SZ",18/03/1967,v*******h99@gmail.com,153,32,31/01/2022,SN0080
96,96,Vincent Lee,male,"903 Pearson underpass, Gregoryberg, WA6 6TY",29/11/1974,v******l@gmail.com,164,59,15/02/2022,SN0096
196,196,Wayne Clark,male,"154 Peter drive, Port Jack, IP17 2HB",05/02/1969,w*******cl40@yahoo.com,162,68,23/01/2022,SN0196
165,165,Wendy Baxter,female,"8 Charlene valleys, Port Damien, M40 1HB",26/05/1983,w****ba@yahoo.com,164,64,05/03/2022,SN0165
198,198,Zoe Williams,female,"17 Janet grove, Ingrambury, RG7 4RJ",06/01/1979,z****w@hotmail.com,162,68,11/02/2022,SN0198

We can reverse the order it's sorted by setting **ascending=False**

In [ ]:
df.sort_values('name', ascending=False)

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
198,198,Zoe Williams,female,"17 Janet grove, Ingrambury, RG7 4RJ",06/01/1979,z****w@hotmail.com,162,68,11/02/2022,SN0198
165,165,Wendy Baxter,female,"8 Charlene valleys, Port Damien, M40 1HB",26/05/1983,w****ba@yahoo.com,164,64,05/03/2022,SN0165
196,196,Wayne Clark,male,"154 Peter drive, Port Jack, IP17 2HB",05/02/1969,w*******cl40@yahoo.com,162,68,23/01/2022,SN0196
96,96,Vincent Lee,male,"903 Pearson underpass, Gregoryberg, WA6 6TY",29/11/1974,v******l@gmail.com,164,59,15/02/2022,SN0096
80,80,Victor Houghton,male,"715 Robert vista, East Conor, FY1 9SZ",18/03/1967,v*******h99@gmail.com,153,32,31/01/2022,SN0080
...,...,...,...,...,...,...,...,...,...,...
94,94,Alison Davies,female,"Flat 35, Keith mountains, Simmonsmouth, N1 4HD",26/08/1964,a*******d@gmail.com,167,66,30/03/2022,SN0094
116,116,Alice Bell,female,"Flat 4, Baker ranch, Port Clare, BT66 8BW",09/05/1999,a*****be@yahoo.com,156,60,15/02/2022,SN0116
133,133,Alan Evans,male,"6 Charlton glens, Hollyton, DH4 7AY",15/03/1974,a******e@yahoo.com,174,42,10/03/2022,SN0133
235,235,Adrian King-Ferguson,male,"Flat 94, Barbara knolls, Brianfort, ME9 8JZ",24/04/1967,a******ki@yahoo.com,157,49,19/01/2022,SN0235
160,160,Adrian Hunter,male,"Flat 4, Adam avenue, Marianburgh, WR13 6PZ",07/09/1966,a*****hu73@gmail.com,173,65,15/03/2022,SN0160

Sort by **multiple columns.**

In [ ]:
df.sort_values(by=['height_cm', 'weight_kg'])

,user_id,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial
125,125,Dr Joe Curtis,male,"066 West junctions, North Mitchell, BT32 5JX",30/07/1996,d*******j@gmail.com,150,42,08/01/2022,SN0125
19,19,Chelsea Ellis-Kelly,female,"Flat 8, Butler ports, North Geraldinemouth, IV...",07/10/1964,c****el@hotmail.com,150,56,27/03/2022,SN0019
180,180,Heather Khan-Smith,female,"583 Rosemary ridges, New Rachel, EH14 5JW",14/01/1973,h*******kh@yahoo.com,151,31,09/12/2021,SN0180
153,153,Tina Thomas,female,"2 Howard valley, Chloeview, EC3M 8AP",14/11/1976,t****t@gmail.com,151,38,01/01/2022,SN0153
197,197,Mr Mohammed Fisher,male,"81 John key, East Cameron, PL1 1DS",02/03/1953,m******m32@hotmail.com,151,43,30/01/2022,SN0197
...,...,...,...,...,...,...,...,...,...,...
29,29,Mr Antony Davey,male,"Studio 90L, Warner track, Mooreport, UB1 2QL",24/10/1961,m*******an@gmail.com,189,71,14/12/2021,SN0029
44,44,Catherine Patel,female,"27 Wilkinson garden, West Edward, SA72 6XQ",22/08/1964,c******p8@gmail.com,189,82,01/01/2022,SN0044
207,207,Mrs Rebecca Iqbal,female,"Studio 54, Yvonne stream, Lake Owenstad, BT44 0DY",24/08/1994,m*******r@yahoo.com,189,85,15/03/2022,SN0207
106,106,Mr Elliott Francis,male,"Studio 1, Julia pike, South Alexandra, B97 5AD",07/02/1948,m******e@gmail.com,189,89,25/03/2022,SN0106
100,100,Mandy Middleton,female,"774 Morton trail, Davidmouth, WF9 4RY",29/09/1971,m*******m@gmail.com,189,100,15/03/2022,SN0100

## **5.2 Pandas GroupBy**

Grouping is the process of **categorising** data based on one or more columns. It allows you to focus your analysis on specific sections of your data.

The `groupby` method in Pandas is a powerful tool for aggregating data into groups based on some criteria. It essentially involves splitting the data into different groups, applying a function to each group independently, and then combining the results.

**Basic Syntax**

The basic syntax for the groupby method is as follows:

- `DataFrame.groupby(by, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=<object>, observed=False)`

**Parameters:**

- **by**: Specifies the columns or a mapping you want to group by. You can also use a function or multiple arrays of the same length.

- **axis**: Determines the axis along which to group (0 for rows and 1 for columns). The default is 0.

- **level**: If the DataFrame has a MultiIndex, you can choose which level to group by.

- **as_index**: When True (the default), the keys you use to group will become an index in the new DataFrame. Set this to False if you want the keys to remain as columns.

- **sort**: Sorts the groups when set to True (the default).

- **group_keys**: Adds a hierarchical index when True, based on the group keys. Useful when you're using apply with the groups.

- **squeeze**: Squeezes the groups to a Series if they contain only one column.

- **observed**: Takes into account only observed categories for Categorical columns when set to True.

In [ ]:
df.groupby(by='gender').mean(numeric_only=True) # Use numeric_only = True, if you want to calculate the mean only for numeric columns

            user_id   height_cm  weight_kg
gender
female   124.308943  169.300813  62.333333
male     122.992000  170.000000  62.592000
unknown  230.500000  153.500000  45.000000

#### **Groupby with multiple columns**

In [ ]:
df.groupby(by=['gender','weight_kg'], sort=True).mean()

<ipython-input-70-b8fa225257fd>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(by=['gender','weight_kg'], sort=True).mean()

                      user_id   height_cm
gender  weight_kg
female  31         180.000000  151.000000
        37          12.000000  154.000000
        38         153.000000  151.000000
        40          71.000000  165.000000
        42         238.000000  154.000000
...                       ...         ...
male    88         168.333333  185.666667
        89         165.000000  181.000000
        100        151.000000  186.000000
unknown 38         242.000000  156.000000
        52         219.000000  151.000000

[96 rows x 2 columns]

**Notice** the heirarchical nature of the output after performing a groupby.

When you perform a groupby operation followed by an aggregation function like sum, mean, etc., and you group by multiple columns, Pandas will return a DataFrame with a **MultiIndex** or **hierarchical index**. A hierarchical index allows you to have multiple levels of columns or rows, making it easier to work with higher dimensional data. However, they can be difficult to work with if you're not used to them.

**Why Hierarchical Indices?**

Hierarchical indices can be very useful when you need to summarize data in a structured and accessible way. For example, you might first group by "Country", and then by "State" within each country. The hierarchical index allows you to easily perform operations at different granularity levels.

**How to Flatten Hierarchical Index**

Use `df.reset_index()`

In [ ]:
df_grouped = df.groupby(by=['gender','weight_kg'], sort=True).mean().reset_index()
df_grouped

<ipython-input-73-c87a21fe963a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_grouped = df.groupby(by=['gender','weight_kg'], sort=True).mean().reset_index()

     gender  weight_kg     user_id   height_cm
0    female         31  180.000000  151.000000
1    female         37   12.000000  154.000000
2    female         38  153.000000  151.000000
3    female         40   71.000000  165.000000
4    female         42  238.000000  154.000000
..      ...        ...         ...         ...
91     male         88  168.333333  185.666667
92     male         89  165.000000  181.000000
93     male        100  151.000000  186.000000
94  unknown         38  242.000000  156.000000
95  unknown         52  219.000000  151.000000

[96 rows x 4 columns]

**List of groupby() functions**
- mean()
- sum()
- size()
- count()
- min()
- max()
- std()
- var()
- first()
- last()

## **5.3 What is Aggregating?**

The `agg` function in Pandas allows you to perform multiple aggregate operations at once or perform different aggregate operations on different columns. The function is highly versatile and can accept a variety of input formats like strings, dictionaries, or even custom functions.

**Syntax: **

- `DataFrame.agg(func, axis=0, *args, **kwargs)`

- `func`: The function or functions to apply. Can be a single function or a list for applying multiple functions.
- `axis`: The axis to apply the function along (0 for applying function to each column).

In [ ]:
df.groupby('gender').agg({
    'height_cm': 'mean',
    'weight_kg': 'min'
})

          height_cm  weight_kg
gender
female   169.300813         31
male     170.000000         32
unknown  153.500000         38

**Differences Between agg and Basic groupby:**

- **Flexibility**: Using agg allows you to perform multiple and different kinds of operations at once, whereas a basic groupby followed by an aggregate function (e.g., mean(), sum()) performs the same operation on all selected columns.

- **Column Specification:** With agg, you can specify which columns to aggregate and how, making it more explicit and readable.

- **Multiple Functions**: agg can apply multiple functions to each column, resulting in a hierarchical index in the output DataFrame.

In [ ]:
# Using agg to specify operations for each column
df.groupby('gender').agg({'height_cm': 'mean', 'weight_kg': ['min', 'max']})

          height_cm weight_kg
               mean       min  max
gender
female   169.300813        31  102
male     170.000000        32  100
unknown  153.500000        38   52

In [ ]:
# Applying multiple functions to 'height_cm' and 'weight_kg'
df.groupby('gender').agg({'height_cm': ['mean', 'max'], 'weight_kg': ['min', 'max']})

          height_cm      weight_kg
               mean  max       min  max
gender
female   169.300813  189        31  102
male     170.000000  189        32  100
unknown  153.500000  156        38   52

## **⌨️Exercise**

1. Group the data by 'gender' and calculate the mean height (height_cm) for each gender.
2. Use the agg function to find both the minimum and maximum weight (weight_kg) for each gender.
3. Extend your use of agg to find the mean height and mean weight, as well as the number of unique bike_serial entries for each gender.
4. (Bonus) For each gender, identify the person (or persons) with the maximum weight. Hint: You might want to use the idxmax() function after grouping.

# **6. Joins and Merging in Pandas**

![image.png]()


## **6.1 Method 1: Using merge() for SQL-like Join**
The merge() function provides a lot of flexibility and control over how you want to combine DataFrames. Here are the parameters we'll focus on:



```
pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False)

```


Here are the some of the parameters we'll focus on:

- **left and right**: The DataFrames you want to merge.
- **how**: Type of merge to be performed. Options include 'left', 'right', 'outer', and 'inner'. The default is 'inner'.
- **on**: Column(s) that should be used to make the join. Must be found in both DataFrames.
- **left_on and right_on**: Columns from the left and right DataFrames to use as keys if the DataFrames do not have the same column for joining.
left_index and right_index: Use the index from the left/right DataFrame as the join key(s). If it is a MultiIndex, the number of keys in the other DataFrame's join keys must match.
- **sort**: Sort the result DataFrame by the join keys in lexicographical order. Defaults to False.



### **Now let's perform our first merge**

# Now let's perform our first merge

```
merged_data = pd.merge(user_data, crm_data, on='user_id')
```


This uses the '**inner**' join method by default and specifies **user_id** as the column common to both DataFrames for merging.

- **left**: This is user_data, the DataFrame that appears as the first argument in pd.merge(). It is one of the two DataFrames you are attempting to merge.

- **right**: This is crm_data, the DataFrame that appears as the second argument in pd.merge(). It is the other DataFrame you are merging with user_data.

- **on**: This specifies the column that both user_data and crm_data share, which in this case is 'user_id'. The merge function uses this column as the key for merging the two DataFrames.

In [ ]:
import pandas as pd

# We can easily load CSV files with Pandas, either from a URL or a file stored on your system.
user_data_csv = 'https://raw.githubusercontent.com/BPP-Digital-Advanced-Data-Analytics/public_datasets/main/fitconstructor/user_data.csv'
crm_data_csv = 'https://raw.githubusercontent.com/BPP-Digital-Advanced-Data-Analytics/public_datasets/main/fitconstructor/crm.csv'

# Load data from a CSV file
user_data = pd.read_csv(user_data_csv)
user_data.drop(columns = 'Unnamed: 10', inplace=True)

crm_data = pd.read_csv(crm_data_csv)
crm_data.head()

,user_id,email,number_of_visit,first_purchase_date,original_source
0,0,m*****ka@yahoo.com,8,31/12/2021,offline
1,1,m*******sa@gmail.com,4,22/12/2021,direct
2,2,l******be@hotmail.com,2,01/03/2022,offline
3,3,m******ki@hotmail.com,6,09/04/2021,offline
4,4,k*****ta@gmail.com,10,26/07/2022,direct

In [ ]:
# Now let's perform our first merge
merged_data = pd.merge(user_data, crm_data, on='user_id')
merged_data

#### **Observe the resulting dataframe merged_data now has all the user_data plus new columns from CRM which are number_of_visit	first_purchase_date	original_source**

- **merged_data:** This is the resulting DataFrame after the merge operation. It will contain all the columns from both user_data and crm_data, and rows will be combined based on the common user_id.

## **6.2 Method 2 - Understanding join() in Pandas**
The `join()` method in Pandas is used to combine rows of two or more data frames based on one or more keys. This method is similar to SQL joins. Here's a breakdown of the syntax and its key parameters:

**Syntax**:


```
DataFrame.join(other, on=None, how='left', lsuffix='', rsuffix='', sort=False)
```

**Parameters:**

- **other:** The DataFrame you want to join with.
- **on:** Column or index level names to join on. These must be found in both DataFrames.
- **how:** Type of join to be executed (left, right, outer, inner). Default is left.
lsuffix and rsuffix: Suffixes to use for overlapping columns from the left and right DataFrames, respectively.
- **sort:** Sort the join keys lexicographically in the result DataFrame. Default is False.

In [ ]:
# Make sure 'user_id' is set as the index for both DataFrames
user_data.set_index('user_id', inplace=True)
crm_data.set_index('user_id', inplace=True)

# Perform the join
joined_data = user_data.join(crm_data)
joined_data

,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial,email,number_of_visit,first_purchase_date,original_source
user_id,,,,,,,,,,,,,
0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR",23/10/1960,m*****ka@yahoo.com,171,49,02/03/2022,SN0000,m*****ka@yahoo.com,8,31/12/2021,offline
1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL",25/09/1995,m*******sa@gmail.com,164,53,29/01/2022,SN0001,m*******sa@gmail.com,4,22/12/2021,direct
2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA",22/03/1966,l******be@hotmail.com,177,87,13/03/2022,SN0002,l******be@hotmail.com,2,01/03/2022,offline
3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA",22/04/1975,m******ki@hotmail.com,179,76,05/12/2021,SN0003,m******ki@hotmail.com,6,09/04/2021,offline
4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU",20/04/1978,k*****ta@gmail.com,182,82,09/02/2022,SN0004,k*****ta@gmail.com,10,26/07/2022,direct
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Miss Janet Thomas,female,"Studio 0, Nicholas viaduct, North Tracey, NP11...",15/04/1997,m******j16@yahoo.com,164,67,20/12/2021,SN0245,m******j16@yahoo.com,4,11/11/2021,direct
246,Elliot Little,male,"6 Akhtar estates, Stevenfort, BN16 3PS",01/03/1944,e*******l@gmail.com,184,88,26/12/2021,SN0246,e*******l@gmail.com,5,30/11/2021,social media
247,Miss Victoria Stevens,female,"Flat 46, Gibbs trafficway, Amandashire, E15 4QB",05/07/1977,m******vi77@yahoo.com,182,69,08/02/2022,SN0247,m******vi77@yahoo.com,3,27/06/2022,offline
248,Sara Griffin,female,"0 Katie vista, Davieshaven, ST5 5AT",24/01/1991,s*******gr@hotmail.com,189,64,15/12/2021,SN0248,s*******gr@hotmail.com,1,04/12/2021,direct
249,Fiona Patel,female,"Studio 0, Patel pine, Mitchellside, LA16 7AA",12/04/1952,f*****pa45@hotmail.com,158,57,21/03/2022,SN0249,f*****pa45@hotmail.com,0,09/02/2022,google ads

## **Method 3: Using concat() for Direct Concatenation**

The **concat()** function is used for stacking DataFrames either vertically or horizontally (technically not merging as not matching by a key is taking place). It is useful when you have DataFrames with similar structures and want to combine them into a single DataFrame.

To concatenate user_data and crm_data vertically:

In [ ]:
concatenated_data = pd.concat([user_data, crm_data], ignore_index=True)
concatenated_data

,name,gender,address,date_of_birth,email_address,height_cm,weight_kg,account_create_date,bike_serial,email,number_of_visit,first_purchase_date,original_source
0,Mrs Katie Hudson,female,"979 Marcus mall, Mitchellside, HP23 5HR",23/10/1960,m*****ka@yahoo.com,171.0,49.0,02/03/2022,SN0000,NaN,NaN,NaN,NaN
1,Mr Sam Simmons,male,"Studio 77U, Arthur lock, Tomchester, NP19 9TL",25/09/1995,m*******sa@gmail.com,164.0,53.0,29/01/2022,SN0001,NaN,NaN,NaN,NaN
2,Lorraine Bentley,female,"Flat 89, Williams avenue, Katieville, CT3 1BA",22/03/1966,l******be@hotmail.com,177.0,87.0,13/03/2022,SN0002,NaN,NaN,NaN,NaN
3,Ms Kimberley Walker,female,"6 Cameron freeway, Beverleymouth, M14 5GA",22/04/1975,m******ki@hotmail.com,179.0,76.0,05/12/2021,SN0003,NaN,NaN,NaN,NaN
4,Kimberley Taylor,female,"Flat 0, Thomas trace, New Tom, KY8 2EU",20/04/1978,k*****ta@gmail.com,182.0,82.0,09/02/2022,SN0004,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,m******j16@yahoo.com,4.0,11/11/2021,direct
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e*******l@gmail.com,5.0,30/11/2021,social media
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,m******vi77@yahoo.com,3.0,27/06/2022,offline
498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s*******gr@hotmail.com,1.0,04/12/2021,direct
499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f*****pa45@hotmail.com,0.0,09/02/2022,google ads

## **⌨️Exercise**

1. Given two DataFrames, user_data and crm_data, both having a column named 'user_id', perform a basic inner merge to combine them.
2. Using the scrm_data and user_Data, concatenate them horizontally and display the resulting DataFrame.